#!/usr/bin/env node
"use strict";
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..');
const expected=['00716','00799','00419','00303','00812','00385','00279','00455','00558','00811','00817','00676','00819','00929','00205','00247','00248','00264','00249','00246','00266','00267','00300','00212','00766','00215','00772','00620','00769','00771','00261','00251','00624','00308','00203','00301','00306','00499','00232','00862','00746','00588','00226','00621','00904','00311','00312','00375'].sort();
function read(f){return JSON.parse(fs.readFileSync(path.join(root,f),'utf8'));}function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const p=path.join(d,e.name);return e.isDirectory()?walk(p):[p];});}
function all(){return walk(path.join(root,'protocols')).filter(f=>f.endsWith('.json')&&!f.includes(`${path.sep}protocols${path.sep}protocols${path.sep}`)&&!['index.json','protocol-schema.json','package.json'].includes(path.basename(f))).map(file=>{try{return {file,data:JSON.parse(fs.readFileSync(file,'utf8'))};}catch{return null;}}).filter(Boolean).filter(x=>x.data?.metadata?.nccp_regimen_code&&x.data.metadata.nccp_regimen_code!=='00000');}
function groups(d){const m=d.metadata||{},o=[];if(typeof m.tumour_group==='string')o.push(m.tumour_group);for(const v of m.tumour_groups||[])if(!o.includes(v))o.push(v);return o;}function demo(d){if(d.demo_value!==undefined&&d.demo_value!==null)return String(d.demo_value);if(d.type==='select')return String(d.options?.[0]?.value??'');if(d.type==='boolean')return 'false';if(d.type==='number')return String(Number.isFinite(Number(d.min))?d.min:0);return 'test';}
const protocols=all(),gyn=protocols.filter(x=>groups(x.data).includes('Gynaecology')),codes=gyn.map(x=>String(x.data.metadata.nccp_regimen_code).padStart(5,'0')).sort();assert.deepStrictEqual(codes,expected);assert.strictEqual(gyn.length,48);assert.strictEqual(new Set(codes).size,48);assert.strictEqual(new Set(protocols.map(x=>x.data.protocol_id)).size, 376);
const index=read('protocols/index.json');assert.strictEqual(index.protocol_count, 376);assert.strictEqual(index.protocols.length, 376);const risk=read('data/emetogenic-risk-map.json');assert.strictEqual(risk.release,'0.48.0');assert.strictEqual(Object.keys(risk.protocols||{}).length,376);
let inputs=0,rules=0,ctcae=0,renal=0;for(const {data} of gyn){const m=data.metadata,code=String(m.nccp_regimen_code).padStart(5,'0');assert.strictEqual(data.status,'encoded_prototype_pending_clinical_and_pharmacy_validation');assert.strictEqual(m.partial_assessment_supported,true);assert(/^https:\/\/healthservice\.hse\.ie\/documents\//.test(m.source_url||''));assert(Array.isArray(data.required_inputs)&&data.required_inputs.length===0);assert(Array.isArray(m.common_trade_names)&&m.common_trade_names.length);assert(risk.protocols[code]);const defs=data.input_definitions||{},rs=data.rule_engine?.rules||[];inputs+=Object.keys(defs).length;rules+=rs.length;assert(Object.keys(defs).length>=8,`${code} insufficient inputs`);assert(rs.length>=7,`${code} insufficient rules`);for(const [id,d] of Object.entries(defs)){assert.strictEqual(d.required,false,`${code}/${id} required`);assert.notStrictEqual(d.demo_value,undefined,`${code}/${id} no demo`);if(d.ctcae_version){ctcae++;assert(d.assessment_guidance);for(let g=0;g<=4;g++){const o=(d.options||[]).find(x=>Number(x.value)===g);assert(o&&o.description,`${code}/${id}/G${g}`);}}if(d.renal_input){renal++;if(d.renal_input.mode==='protocol_specific_band'){assert.strictEqual(d.renal_input.exact_value_required,false);}else{assert.strictEqual(d.renal_input.mode,'exact_continuous');const drugs=(m.drugs||[]).join(' ').toLowerCase();assert(drugs.includes('carboplatin')||/gfr|calvert|carboplatin/i.test(`${id} ${d.label||''}`),`${code}/${id} exact renal input not justified`);}}}const title=m.title||'';assert(!/(CARBOplatin|PACLitaxel|CISplatin|DOXOrubicin|DOCEtaxel|DACTINomycin|vinCRIStine|prednisoLONE)/.test(title),`${code} mixed-case title`);}
assert(inputs>=650);assert(rules>=600);assert(ctcae>=60);assert(renal>=15);
const by=c=>gyn.find(x=>String(x.data.metadata.nccp_regimen_code).padStart(5,'0')===c).data;assert(by('00624').input_definitions.anc.required===false);assert(by('00419').input_definitions.gfr_or_crcl_ml_min);assert(by('00819').input_definitions.tsh_miu_l?.required===false);assert(by('00819').input_definitions.free_t4_pmol_l?.required===false);assert(by('00929').input_definitions.tsh_miu_l?.required===false);assert(by('00746').metadata.common_trade_names.includes('Lynparza'));assert(by('00904').metadata.common_trade_names.includes('Rubraca'));assert(by('00246').metadata.common_trade_names.includes('Charing Cross regimen'));
const ctx={console};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'js/rule-engine.js'),'utf8'),ctx);vm.runInContext(fs.readFileSync(path.join(root,'js/assessment-engine.js'),'utf8'),ctx);const Engine=ctx.SACTCheckAssessmentEngine,RuleEngine=ctx.SACTCheckRuleEngine;let audited=0;
for(const {data} of gyn){const profileId=Engine.getProfiles(data)[0]?.id||'default',defs=Engine.getInputDefinitions(data,profileId,{}),fields=new Set((data.rule_engine?.rules||[]).flatMap(r=>RuleEngine.collectConditionFields(RuleEngine.conditionFromRule(r)))),candidates=defs.filter(d=>d.visible!==false&&fields.has(d.id)&&demo(d)!=='');assert(candidates.length>0,`${data.protocol_id} no auditable inputs`);for(const d of candidates){const result=Engine.assess(data,{[d.id]:demo(d)},{profileId});assert(result.findings.length>0,`${data.protocol_id}/${d.id} no finding`);assert(!/insufficient data/i.test(String(result.status||'')));audited++;}}
assert(audited>=500,`single-entry checks ${audited}`);const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert(html.includes('v0.55.0 · What changed?'));assert(html.includes('js/protocol-loader.js?v=0.51.0'));const tissue=fs.readFileSync(path.join(root,'js/tissue-ui.js'),'utf8');assert(tissue.includes('label: "Gynaecology"'));console.log(`v0.43.0 Gynaecology tests passed: ${gyn.length} protocols, ${inputs} inputs, ${rules} rules, ${audited} single-entry checks.`);
