"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const Engine=require("../js/assessment-engine.js");
const Validator=require("../js/protocol-validator.js");
const root=path.join(__dirname,"..");
const index=JSON.parse(fs.readFileSync(path.join(root,"protocols/index.json"),"utf8"));
const ids=["nccp-00270-v3a","nccp-00435-v3","nccp-00416-v4","nccp-00643-v3","nccp-00275-v3"];
assert.strictEqual(index.protocol_count,376);
const entries=ids.map(id=>{const hit=index.protocols.filter(item=>item.id===id);assert.strictEqual(hit.length,1,`${id} catalogue duplication/missing`);return hit[0];});
let inputs=0,rules=0;
for(const entry of entries){
  assert.strictEqual(entry.tumour_group,"Haematology");
  const protocol=JSON.parse(fs.readFileSync(path.join(root,entry.path),"utf8"));
  const validation=Validator.validate(protocol,{strict:true});
  assert.strictEqual(validation.valid,true,Validator.formatIssues(validation).join("\n"));
  assert.deepStrictEqual(protocol.required_inputs,[]);
  assert(Object.values(protocol.input_definitions).every(def=>def.required===false));
  assert.strictEqual(protocol.metadata.catalogue_section,"haem_plasma_cell_disorders");
  assert.strictEqual(protocol.metadata.validation.clinical_use_authorised,false);
  inputs+=Object.keys(protocol.input_definitions).length; rules+=protocol.rule_engine.rules.length;
  const defs=Engine.getInputDefinitions(protocol,"default",{});
  const candidate=defs.find(def=>["anc_x10e9_l","platelets_x10e9_l","crcl_ml_min","neuropathy_grade"].includes(def.id));
  assert(candidate,`${entry.id} lacks a partial-assessment candidate`);
  const result=Engine.assess(protocol,{[candidate.id]:candidate.demo_value},{profileId:"default"});
  assert.strictEqual(result.complete,false,`${entry.id} single value should remain partial`);
  assert(result.findings.length>0,`${entry.id} single value should produce a finding`);
  assert(result.unassessed.length>0,`${entry.id} should identify unassessed domains`);
}
assert.strictEqual(inputs,78);
assert.strictEqual(rules,80);
const p270=JSON.parse(fs.readFileSync(path.join(root,"protocols/haemato-oncology/plasma-cell/00270-bortezomib-dexamethasone.json"),"utf8"));
assert(p270.input_definitions.platelets_x10e9_l);
assert.strictEqual(Engine.assess(p270,{platelets_x10e9_l:20},{profileId:"default"}).actionType,"withhold_then_reduce");
const p416=JSON.parse(fs.readFileSync(path.join(root,"protocols/haemato-oncology/plasma-cell/00416-rvd-21-day.json"),"utf8"));
assert(p416.input_definitions.acute_diffuse_infiltrative_pulmonary_or_pericardial_disease);
assert(!p416.input_definitions.pregnancy_or_breastfeeding);
assert.strictEqual(Engine.assess(p416,{acute_diffuse_infiltrative_pulmonary_or_pericardial_disease:true},{profileId:"default"}).actionType,"contraindicated");
const p275=JSON.parse(fs.readFileSync(path.join(root,"protocols/haemato-oncology/plasma-cell/00275-bortezomib-melphalan-prednisolone.json"),"utf8"));
assert(p275.input_definitions.previous_cycle_thrombocytopenia_with_bleeding);
assert.strictEqual(Engine.assess(p275,{previous_cycle_thrombocytopenia_with_bleeding:true},{profileId:"default"}).actionType,"dose_reduce");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
assert(html.includes('data-library-domain-choice="haem"'));
assert(html.includes('js/haemato-oncology.js?v=0.50.0'));
assert(html.includes('js/protocol-loader.js?v=0.50.0'));
const loader=fs.readFileSync(path.join(root,"js/protocol-loader.js"),"utf8");
assert(loader.includes('haem_plasma_cell_disorders'));
assert(loader.includes('dataset.libraryDomain'));
console.log(`v0.49.0 haem foundation passed: ${entries.length} protocols, ${inputs} optional inputs, ${rules} rules.`);
