'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..');
const profile=require('../data/patient-knowledge/00568.json');
const registry=require('../js/patient-asset-registry-v0810.js');
const protocol=require('../protocols/lung/00568-pembrolizumab-pemetrexed-and-carboplatin-auc5-therapy.json');
assert.equal(profile.protocol_id,protocol.protocol_id);
assert.equal(registry.relativePath(protocol,'knowledge'),'patient/00568/knowledge.html');
assert.equal(registry.relativePath(protocol,'consent-draft'),'patient/00568/consent.html');
assert.equal(registry.relativePath('00209','consent-draft'),null,'unsupported drafts must not silently resolve to patient portals');
assert.deepEqual(profile.phases[0].agents,['pembrolizumab','pemetrexed','carboplatin']);
assert.deepEqual(profile.phases[1].agents,['pembrolizumab','pemetrexed']);
assert.equal(profile.cycle_days,21);
assert.equal(profile.timeline.find(r=>r.id==='immune').end,21);
cp.execFileSync(process.execPath,['tools/build-patient-knowledge.cjs','--check'],{cwd:root,stdio:'inherit'});
const code=fs.readFileSync(path.join(root,'assets/patient/patient-knowledge.js'),'utf8');
assert.doesNotMatch(code,/localStorage|sessionStorage|fetch\(|XMLHttpRequest|sendBeacon/,'patient date must not persist or transmit');
let opened='';global.open=url=>{opened=url;return {};};
const workflow=require('../js/regimen-workflow-engine-v0750.js');
workflow.openConsentSupport(protocol);assert.match(opened,/patient\/00568\/consent\.html$/);
console.log('Patient knowledge contract, generated-page freshness, phase selection and consent routing passed.');
