const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'css','search-first-v0570.css'),'utf8');
const ui=fs.readFileSync(path.join(root,'js','search-first-v0570.js'),'utf8');
const search=require(path.join(root,'js','regimen-search.js'));
assert.ok(html.includes('SACTCheck v0.57.0 — Search-First Library'), 'Historical search-first label should remain for regression traceability.');
assert.ok(html.includes('SACTCheck v0.58.0 — Ten-Regimen Knowledge Base'));
assert.ok(html.includes('id="libraryCatalogueSection"'));
assert.ok(html.includes('id="clinicalScenarioLauncher"'));
assert.ok(html.includes('scenario-collapsed'));
assert.ok(html.includes('setTimeout(()=>filterRegimens(),175)'));
assert.ok(css.includes('.search-first-catalogue'));
assert.ok(ui.includes("insertBefore(catalogue,hero)"));
assert.strictEqual(search.performanceVersion,'0.57.0');
const exact={dataset:{name:'bevacizumab avastin'},querySelector(){return {textContent:'Bevacizumab'}},textContent:'Bevacizumab NCCP 00593 ovarian'};
assert.ok(search.rankCards([exact],'bevacizumab').length===1);
assert.ok(search.rankCards([exact],'bevicizumab').length===1,'Conditional fuzzy matching should retain common close spelling matches.');
console.log('v0.57.0 search-first tests passed.');
