'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require(process.env.SACT_PLAYWRIGHT_MODULE||'playwright');
(async()=>{const root=path.resolve(__dirname,'..'),server=await require('../tools/local-site-server.cjs').serve(process.env.SACT_SITE_DIR||root);const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-gpu']});const results=[];
try{for(const width of [1440,390]){const context=await browser.newContext({viewport:{width,height:950}}),p=await context.newPage();p.setDefaultTimeout(15000);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.__opens=[];const open=window.open;window.open=(u,...a)=>{window.__opens.push(String(u));return open.call(window,u,...a)}});
for(const load of ['cold','warm']){await (load==='cold'?p.goto(server.url):p.reload());await p.waitForFunction(()=>document.querySelector('.regimen-card[data-json-protocol-id="nccp-00568-v5"]')?.dataset.sactCardReady==='true',{},{timeout:30000});await p.locator('#regimenSearch').fill('00568');const card=p.locator('.regimen-card[data-json-protocol-id="nccp-00568-v5"]');assert.ok(await card.isVisible());assert.ok(await card.locator('[data-open-regimen-workflow]').isVisible());assert.ok(await card.locator('[data-open-patient-support]').isVisible());results.push({width,load,completeCard:true});}
await p.waitForTimeout(1500);
const mutations=await p.evaluate(()=>new Promise(resolve=>{const card=document.querySelector('.regimen-card[data-json-protocol-id="nccp-00568-v5"]');let count=0;const observer=new MutationObserver(m=>count+=m.length);observer.observe(card,{childList:true,subtree:true});for(let i=0;i<10;i++)SACTCheckInterface.decorateCards();setTimeout(()=>{observer.disconnect();resolve(count)},1000)}));assert.equal(mutations,0,'repeated decoration and idle card must not rewrite children');
const card=p.locator('.regimen-card[data-json-protocol-id="nccp-00568-v5"]');await card.locator('[data-open-patient-support]').click();await p.waitForFunction(()=>window.__opens.some(u=>u.endsWith('/patient/00568/guide.pdf')));for(const q of context.pages())if(q!==p)await q.close();
await card.locator('[data-open-regimen-workflow]').click();assert.ok(await p.locator('#workflowPanelBody').isVisible());await p.locator('button[data-close-workflow]').click();
await card.locator('.json-assessment-launch').click();await p.locator('#jsonInput_anc_x10e9_l').fill('0.8');await p.getByRole('button',{name:'Run JSON protocol assessment',exact:true}).click();const result=await p.locator('#jsonResult').innerText();assert.ok(result.includes('0.8'));assert.match(result,/hold|delay|defer|withhold|do not proceed|do not administer/i);assert.match(result,/not assessed|unassessed|not entered|not provided|missing/i);
assert.deepEqual(errors,[]);results.push({width,idleAndRepeatedDecorationMutations:mutations,guidePDF:true,workflow:true,ancOnly:true,assessment:result.slice(0,1600)});await context.close();}
fs.mkdirSync(path.join(root,'validation'),{recursive:true});fs.writeFileSync(path.join(root,'validation/ui-reliability-v0818.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));}finally{await browser.close();await server.close();}})().catch(e=>{console.error(e);process.exit(1)});
