"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path");
const root=path.resolve(__dirname,"..");const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const pkg=require(path.join(root,"package.json"));const app=require(path.join(root,"data/app-release.json"));
assert.ok(pkg.version.localeCompare("0.81.2",undefined,{numeric:true})>=0,"v0.81.2 anatomy architecture must remain present in later patch releases");assert.strictEqual(app.version,pkg.version);assert.strictEqual(app.release,pkg.version);
const css=read("assets/patient/guide-v0812.css");assert.ok(css.includes("1.65fr"),"guide anatomy column must remain wide enough to prevent image letterboxing");
const portal=read("patient/00568/index.html");
for(const marker of ['data-hcc-pin="heart" style="left:52.5%;top:28.3%"','data-hcc-pin="liver" style="left:43%;top:33%"','data-hcc-pin="kidneys" style="left:39.5%;top:38.6%"','data-hcc-pin="bowel" style="left:50%;top:44.5%"','data-hcc-pin="vessels" style="left:61.5%;top:61.5%"'])assert.ok(portal.includes(marker),`00568 anatomical anchor missing ${marker}`);
const guide=read("patient/00568/guide.html");assert.ok(guide.includes('guide.pdf'),"00568 guide wrapper must point to protected guide PDF");
const legacy=read("tests/patient-support-v0750.test.js");assert.ok(legacy.includes("global.SACTCHECK_RELEASE||'0.78.0'"),"legacy patient-support release assertion must tolerate the canonical app release");
console.log(`v${pkg.version} cumulative anatomy/deployment regression passed.`);
