"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const read = rel => fs.readFileSync(path.join(root, rel), "utf8");
const readJson = rel => JSON.parse(read(rel));
const pkg = readJson("package.json");
const app = readJson("data/app-release.json");
const html = read("index.html");
assert.strictEqual(pkg.version, "0.67.1");
assert.strictEqual(app.release, pkg.version);
assert.ok(html.includes(`<meta name="sactcheck-release" content="${pkg.version}">`));
assert.ok(html.includes(`<span class="header-version">v${pkg.version}</span>`));
assert.ok(html.includes(`SACTCheck v${pkg.version} · Feasibility evaluation build`));
assert.ok(html.includes(`js/nccp-change-tracker.js?v=0.62.1&app=${pkg.version}`));
assert.ok(html.includes(`js/regimen-knowledge-base.js?v=0.67.0&app=${pkg.version}`));
assert.ok(html.includes(`js/clinical-validation-workspace.js?v=0.67.0&app=${pkg.version}`));
const trackerJs = read("js/nccp-change-tracker.js");
assert.ok(trackerJs.includes('version: "0.62.1"'));
assert.ok(trackerJs.includes('appVersion:'));
assert.strictEqual(readJson("data/nccp-change-tracker/change-feed.json").release, "0.62.1");
assert.strictEqual(readJson("data/regimen-knowledge-base-v0670.json").release, "0.67.0");
assert.strictEqual(readJson("data/clinical-validation-register-v0630.json").release, "0.67.0");
console.log("v0.67.1 public release and module version separation tests passed.");
