#!/usr/bin/env python3
from __future__ import annotations
import json, copy
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
FILES=[p for p in (ROOT/'protocols').rglob('*.json') if p.name!='index.json' and '_template' not in p.parts]

def load(code):
    for p in FILES:
        try:d=json.loads(p.read_text())
        except Exception:continue
        if str(d.get('metadata',{}).get('nccp_regimen_code','')).zfill(5)==code:
            return p,d
    raise KeyError(code)

def write(p,d):
    p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')

def boolean(label,demo=False,help_text=None):
    x={'label':label,'type':'boolean','required':False,'demo_value':demo}
    if help_text:x['help_text']=help_text
    return x

def number(label,demo,unit='',step=.1,minv=0):
    x={'label':label,'type':'number','required':False,'min':minv,'step':step,'demo_value':demo}
    if unit:x['unit']=unit
    return x

def select(label,opts,demo,help_text=None):
    x={'label':label,'type':'select','required':False,'options':[{'value':v,'label':l} for v,l in opts],'demo_value':demo}
    if help_text:x['help_text']=help_text
    return x

def renal(label,opts,demo):
    x=select(label,opts,demo);x['renal_input']={'mode':'protocol_specific_band','exact_value_required':False};return x

def grade(label,cat,guidance):
    return {'label':label,'type':'select','required':False,'options':[{'value':g,'label':f'Grade {g}','ctcae_grade':g} for g in range(5)],'demo_value':0,'ctcae_version':'5.0','ctcae_category':cat,'ctcae_source_url':'https://dctd.cancer.gov/research/ctep-trials/for-sites/adverse-events/ctcae-v5-5x7.pdf','assessment_guidance':guidance}

def r(rid,field,op,value,atype,msg,priority=8,components=None,page='Dose modification section'):
    return {'id':rid,'priority':priority,'when':{'field':field,'operator':op,'value':value},'action':{'type':atype,'components':components or ['whole_regimen'],'message':msg},'source':{'document':'Current official NCCP regimen','page':page},'explanation':msg}

def anyr(rid,leaves,atype,msg,priority=10,page='Eligibility/exclusions section'):
    return {'id':rid,'priority':priority,'when':{'any':leaves},'action':{'type':atype,'components':['whole_regimen'],'message':msg},'source':{'document':'Current official NCCP regimen','page':page},'explanation':msg}

def common(d,ecog_max=2):
    defs=d.setdefault('input_definitions',{})
    defs.setdefault('ecog',select('ECOG performance status',[(0,'0'),(1,'1'),(2,'2'),(3,'3'),(4,'4')],0))
    defs.setdefault('hypersensitivity',boolean('Known hypersensitivity to a regimen component'))
    defs.setdefault('pregnancy',boolean('Pregnant'))
    defs.setdefault('breastfeeding',boolean('Breastfeeding'))
    return [
      r('ECOG_OUTSIDE_SOURCE_RANGE','ecog','>',ecog_max,'consultant_review',f'ECOG above {ecog_max} is outside the usual source eligibility range; verify the indication and current NCCP regimen.',8,page='Eligibility section'),
      r('HYPERSENSITIVITY','hypersensitivity','==',True,'contraindicated','Known hypersensitivity to a regimen component triggers the source exclusion pathway.',10,page='Exclusions section'),
      anyr('PREGNANCY_BREASTFEEDING',[{'field':'pregnancy','operator':'==','value':True},{'field':'breastfeeding','operator':'==','value':True}],'contraindicated','Pregnancy or breastfeeding is outside the routine source pathway.',10)
    ]

def counts(d,anc_demo=2,plt_demo=150):
    defs=d['input_definitions'];defs['anc_x10e9_l']=number('Absolute neutrophil count',anc_demo,'×10⁹/L',.1);defs['platelets_x10e9_l']=number('Platelet count',plt_demo,'×10⁹/L',1)

def standard_toxicity(d):
    defs=d['input_definitions'];defs.setdefault('active_infection',boolean('Active infection requiring treatment'));defs.setdefault('febrile_neutropenia',boolean('Febrile neutropenia or neutropenic sepsis during the previous interval'));defs.setdefault('mucositis_grade',grade('Mucositis/stomatitis grade','mucositis','Assess pain, ulceration and the effect on oral intake; distinguish altered diet from inability to eat or drink.'));defs.setdefault('other_nonhaem_toxicity_grade',grade('Worst relevant non-haematological toxicity','other_nonhaematological','Identify the exact adverse event and apply its own CTCAE criteria, intervention requirement and functional impact.'))

def anthracycline(d):
    defs=d['input_definitions'];defs['lvef_percent']=number('LVEF',60,'%',1);defs['lvef_reduction_from_baseline_percent']=number('Absolute LVEF reduction from baseline',0,'percentage points',1);defs['symptomatic_cardiac_dysfunction']=boolean('Symptoms or signs of cardiac dysfunction');defs['cumulative_anthracycline_mg_m2']=number('Lifetime cumulative anthracycline exposure',0,'mg/m²',1);defs['bilirubin_uln_multiple']=number('Bilirubin result (enter actual result; ×ULN calculated automatically)',1,'×ULN',.01)

def ifos(d):
    defs=d['input_definitions'];defs['ifosfamide_renal_band']=renal('Renal function for ifosfamide',[('ge50','CrCl ≥50 mL/min'),('lt50','CrCl <50 mL/min'),('dialysis','Dialysis')],'ge50');defs['encephalopathy_grade']=grade('Ifosfamide-associated encephalopathy/neurotoxicity grade','neurological_toxicity','Assess confusion, somnolence, agitation, hallucinations, seizures, consciousness and effect on self-care; exclude metabolic, infectious and drug causes.');defs['haematuria']=boolean('Haematuria before or during ifosfamide');defs['urine_output_below_target']=boolean('Urine output below protocol/local hydration target');defs['fluid_balance_positive_over_1l_or_weight_gain_1kg']=boolean('Positive fluid balance >1 L or weight gain >1 kg')

def setrules(d,rules):
    d.setdefault('rule_engine',{})['rules']=rules;d['rule_engine']['conflict_policy']='most_restrictive_action_wins';d['rule_engine']['missing_data_policy']='report_unassessed_coverage_gap';d['required_inputs']=[]

def sourcemeta(d,version,url):
    m=d['metadata'];m['nccp_version']=str(version);m['source_url']=url;m['sactcheck_encoding_version']='0.41.0';m['partial_assessment_supported']=True;d['protocol_id']=f"nccp-{str(m['nccp_regimen_code']).zfill(5)}-v{version}";d['clinical_governance']['disclaimer']=f"Decision-support encoding derived from NCCP {str(m['nccp_regimen_code']).zfill(5)} Version {version}. It does not replace the current official regimen, prescribing review, pharmacy verification or independent clinical judgement."

def support(d,risk,script):
    sc=d['supportive_care'];sc['emetogenic_risk']=risk;sc['script_id']=script;sc['supportive_medications_label']=risk.replace('_',' ').title()+' emetogenic-risk guidance';sc['supportive_medications_pdf_url']='https://healthservice.hse.ie/documents/7152/Classification_Document_for_Systemic_Anti-_Cancer_Therapy_SACT_Induced_Nausea__pWgDCrm.pdf'

# 00511 dacarbazine
p,d=load('00511');counts(d);standard_toxicity(d);defs=d['input_definitions'];defs['dacarbazine_renal_band']=renal('Renal function for dacarbazine',[('gt60','CrCl >60 mL/min'),('45_60','CrCl 45–60 mL/min'),('30_44','CrCl 30–44 mL/min'),('lt30','CrCl <30 mL/min'),('dialysis','Dialysis')],'gt60')
rules=common(d)+[
 r('ANC_LT1','anc_x10e9_l','<',1,'delay','ANC <1.0 ×10⁹/L: delay one week and repeat bloods.',10),r('PLT_LT70','platelets_x10e9_l','<',70,'delay','Platelets <70 ×10⁹/L: delay one week and repeat bloods.',10),r('ANC_1_TO_LT1_5','anc_x10e9_l','<',1.5,'dose_reduce','ANC 1.0–<1.5 ×10⁹/L: administer 80% dacarbazine.',8,['dacarbazine']),r('PLT_70_TO_LT100','platelets_x10e9_l','<',100,'dose_reduce','Platelets 70–<100 ×10⁹/L: administer 80% dacarbazine.',8,['dacarbazine']),r('FN_REDUCE','febrile_neutropenia','==',True,'dose_reduce','After neutropenic sepsis, administer 80% of the previous dacarbazine dose.',9,['dacarbazine']),r('ACTIVE_INFECTION','active_infection','==',True,'withhold','Withhold and treat active infection before dacarbazine.',10),r('DAC_CRCL_45_60','dacarbazine_renal_band','==','45_60','dose_reduce','CrCl 45–60 mL/min: administer 80% dacarbazine.',8,['dacarbazine']),r('DAC_CRCL_30_44','dacarbazine_renal_band','==','30_44','dose_reduce','CrCl 30–44 mL/min: administer 75% dacarbazine.',9,['dacarbazine']),r('DAC_CRCL_LT30','dacarbazine_renal_band','==','lt30','dose_reduce','CrCl <30 mL/min: administer 70% dacarbazine with specialist review.',9,['dacarbazine']),r('DAC_DIALYSIS','dacarbazine_renal_band','==','dialysis','consultant_review','Dialysis requires specialist oncology-pharmacy dosing and timing review.',10),r('NONHAEM_G3','other_nonhaem_toxicity_grade','>=',3,'withhold','Grade ≥3 non-haematological toxicity: withhold until recovery and review dose modification.',9)]
setrules(d,rules);support(d,'high','nccp-parenteral-high');write(p,d)

# 00420 doxorubicin/cisplatin
p,d=load('00420');counts(d);standard_toxicity(d);anthracycline(d);defs=d['input_definitions'];defs['cisplatin_renal_band']=renal('Renal function for cisplatin',[('ge60','CrCl ≥60 mL/min'),('50_59','CrCl 50–59 mL/min'),('40_49','CrCl 40–49 mL/min'),('lt40','CrCl <40 mL/min'),('dialysis','Dialysis')],'ge60');defs['neuropathy_grade']=grade('Peripheral neuropathy grade','neuropathy','Assess sensory and motor symptoms, gait, dexterity and impact on instrumental or self-care activities.');defs['hearing_or_tinnitus']=boolean('Clinically significant hearing impairment or tinnitus');defs['magnesium_low_or_replacement_needed']=boolean('Hypomagnesaemia or electrolyte replacement required')
rules=common(d)+[
 r('ANC_LT1','anc_x10e9_l','<',1,'delay','ANC <1.0 ×10⁹/L: delay treatment.',10),r('PLT_LT70','platelets_x10e9_l','<',70,'delay','Platelets <70 ×10⁹/L: delay treatment.',10),r('ANC_1_1_5','anc_x10e9_l','<=',1.5,'dose_reduce','ANC 1.0–1.5 ×10⁹/L: administer 80% of doxorubicin and cisplatin.',8,['doxorubicin','cisplatin']),r('PLT_70_100','platelets_x10e9_l','<=',100,'dose_reduce','Platelets 70–100 ×10⁹/L: administer 80% of doxorubicin and cisplatin.',8,['doxorubicin','cisplatin']),r('FN_DOX','febrile_neutropenia','==',True,'dose_reduce','Febrile neutropenia with ANC nadir <0.5 ×10⁹/L: reduce doxorubicin to 80%; cisplatin remains 100%.',9,['doxorubicin']),r('DOX_BILI_GT4_3','bilirubin_uln_multiple','>',4.3,'contraindicated','Bilirubin >86 µmol/L / Child-Pugh C: doxorubicin not recommended.',10,['doxorubicin']),r('DOX_BILI_GT2_5','bilirubin_uln_multiple','>',2.5,'dose_reduce','Bilirubin 51–86 µmol/L: administer 25% doxorubicin.',9,['doxorubicin']),r('DOX_BILI_GT1','bilirubin_uln_multiple','>',1,'dose_reduce','Bilirubin 20–50 µmol/L: administer 50% doxorubicin.',8,['doxorubicin']),r('CIS_50_59','cisplatin_renal_band','==','50_59','dose_reduce','CrCl 50–59 mL/min: administer 75% cisplatin.',8,['cisplatin']),r('CIS_40_49','cisplatin_renal_band','==','40_49','dose_reduce','CrCl 40–49 mL/min: administer 50% cisplatin.',9,['cisplatin']),r('CIS_LT40','cisplatin_renal_band','==','lt40','contraindicated','CrCl <40 mL/min: cisplatin is not recommended.',10,['cisplatin']),r('CIS_DIALYSIS','cisplatin_renal_band','==','dialysis','contraindicated','Dialysis is outside the routine cisplatin pathway.',10,['cisplatin']),r('MUCOSITIS_G3','mucositis_grade','>=',3,'dose_reduce','Grade ≥3 mucositis: reduce doxorubicin to 80% after recovery.',9,['doxorubicin']),r('NEURO_G2','neuropathy_grade','>=',2,'omit','Grade ≥2 peripheral neuropathy: omit cisplatin.',10,['cisplatin']),r('CARDIAC_SYMPTOMS','symptomatic_cardiac_dysfunction','==',True,'withhold','Withhold doxorubicin and obtain urgent cardiac assessment.',10,['doxorubicin']),r('LVEF_LOW','lvef_percent','<',50,'withhold','LVEF <50% requires repeat/consultant cardiac review before further anthracycline.',9,['doxorubicin']),r('HEARING','hearing_or_tinnitus','==',True,'consultant_review','Clinically significant hearing impairment/tinnitus requires cisplatin review.',8,['cisplatin']),r('MAGNESIUM','magnesium_low_or_replacement_needed','==',True,'proceed_with_caution','Correct magnesium/electrolytes and apply the hydration pathway.',6,['cisplatin'])]
setrules(d,rules);support(d,'high','nccp-parenteral-high');write(p,d)

# Doxorubicin + ifosfamide pair
for code in ['00391','00392']:
 p,d=load(code);counts(d);standard_toxicity(d);anthracycline(d);ifos(d);rules=common(d,1)+[
  r('ANC_LT1','anc_x10e9_l','<',1,'delay','ANC <1.0 ×10⁹/L: delay treatment.',10),r('PLT_LT70','platelets_x10e9_l','<',70,'delay','Platelets <70 ×10⁹/L: delay treatment.',10),r('ANC_1_1_5','anc_x10e9_l','<=',1.5,'dose_reduce','ANC 1.0–1.5 ×10⁹/L: administer 80% of doxorubicin and ifosfamide.',8,['doxorubicin','ifosfamide']),r('PLT_70_100','platelets_x10e9_l','<=',100,'dose_reduce','Platelets 70–100 ×10⁹/L: administer 80% of doxorubicin and ifosfamide.',8,['doxorubicin','ifosfamide']),r('FN_REDUCE','febrile_neutropenia','==',True,'dose_reduce','ANC nadir <0.5 ×10⁹/L with neutropenic fever: reduce both drugs to 80%.',9,['doxorubicin','ifosfamide']),r('DOX_BILI_GT4_3','bilirubin_uln_multiple','>',4.3,'contraindicated','Bilirubin >86 µmol/L / Child-Pugh C: doxorubicin not recommended.',10,['doxorubicin']),r('DOX_BILI_GT2_5','bilirubin_uln_multiple','>',2.5,'dose_reduce','Bilirubin 51–86 µmol/L: administer 25% doxorubicin.',9,['doxorubicin']),r('DOX_BILI_GT1','bilirubin_uln_multiple','>',1,'dose_reduce','Bilirubin 20–50 µmol/L: administer 50% doxorubicin.',8,['doxorubicin']),r('IFO_RENAL_LT50','ifosfamide_renal_band','==','lt50','consultant_review','CrCl <50 mL/min: ifosfamide is not routinely recommended; consultant/pharmacy decision required.',10,['ifosfamide']),r('IFO_DIALYSIS','ifosfamide_renal_band','==','dialysis','consultant_review','Dialysis: ifosfamide is not routinely recommended.',10,['ifosfamide']),r('MUCOSITIS_G3','mucositis_grade','>=',3,'dose_reduce','Grade ≥3 mucositis: reduce doxorubicin and ifosfamide to 80% after recovery.',9,['doxorubicin','ifosfamide']),r('IFO_NEURO_G3','encephalopathy_grade','>=',3,'permanently_discontinue','Grade ≥3 ifosfamide neurotoxicity: discontinue ifosfamide.',10,['ifosfamide']),r('IFO_HAEMATURIA','haematuria','==',True,'withhold','Haematuria requires withholding ifosfamide and evaluation of urothelial toxicity.',10,['ifosfamide']),r('IFO_URINE','urine_output_below_target','==',True,'withhold','Inadequate urine output requires correction before continuing ifosfamide.',9,['ifosfamide']),r('IFO_FLUID','fluid_balance_positive_over_1l_or_weight_gain_1kg','==',True,'withhold','Positive fluid balance >1 L or weight gain >1 kg requires hydration review before continuing.',9,['ifosfamide'])]
 setrules(d,rules);support(d,'high','nccp-parenteral-high');write(p,d)

# 00500 doxorubicin v3
p,d=load('00500');sourcemeta(d,'3','https://healthservice.hse.ie/documents/6738/500_V3_DOXOrubicin_75.pdf');counts(d);standard_toxicity(d);anthracycline(d);defs=d['input_definitions'];defs['treatment_delay_days']=number('Current treatment delay',0,'days',1);defs['febrile_neutropenia_occurrences']=select('Febrile neutropenia occurrence',[(0,'None'),(1,'First occurrence'),(2,'Second or later occurrence')],0);defs['doxorubicin_renal_band']=renal('Renal function for doxorubicin',[('gt10','CrCl >10 mL/min'),('le10','CrCl ≤10 mL/min, not dialysis'),('dialysis','Haemodialysis')],'gt10')
rules=common(d)+[
 r('ANC_LT1','anc_x10e9_l','<',1,'delay','ANC <1.0 ×10⁹/L: delay one week and reassess.',10),r('PLT_LT100','platelets_x10e9_l','<',100,'delay','Platelets <100 ×10⁹/L: delay one week and reassess.',10),r('DELAY_GT14','treatment_delay_days','>',14,'dose_reduce','Delay >2 weeks: consider one dose-level reduction or discontinuation.',9,['doxorubicin']),r('FN_FIRST','febrile_neutropenia_occurrences','==',1,'consultant_review','First febrile-neutropenia occurrence: consider G-CSF support.',8),r('FN_SECOND','febrile_neutropenia_occurrences','>=',2,'dose_reduce_one_level','Second or later febrile-neutropenia occurrence: reduce doxorubicin by one dose level.',9,['doxorubicin']),r('DOX_HD','doxorubicin_renal_band','==','dialysis','dose_reduce','Haemodialysis: consider 75% doxorubicin with specialist timing review.',9,['doxorubicin']),r('DOX_BILI_GT4_3','bilirubin_uln_multiple','>',4.3,'contraindicated','Bilirubin >86 µmol/L: doxorubicin not recommended.',10,['doxorubicin']),r('DOX_BILI_GT2_5','bilirubin_uln_multiple','>',2.5,'dose_reduce','Bilirubin 51–86 µmol/L: administer 25% doxorubicin.',9,['doxorubicin']),r('DOX_BILI_GT1','bilirubin_uln_multiple','>',1,'dose_reduce','Bilirubin 20–50 µmol/L: administer 50% doxorubicin.',8,['doxorubicin']),r('LVEF_LT45','lvef_percent','<',45,'permanently_discontinue','LVEF <45%: discontinue doxorubicin.',10,['doxorubicin']),r('LVEF_DROP_GT20','lvef_reduction_from_baseline_percent','>',20,'permanently_discontinue','LVEF reduction >20 percentage points from baseline: discontinue doxorubicin.',10,['doxorubicin']),r('OTHER_G3_4','other_nonhaem_toxicity_grade','>=',3,'withhold_then_reduce','Grade 3–4 non-haematological toxicity: hold until Grade ≤1, then consider reduction or discontinuation.',9,['doxorubicin']),r('ACTIVE_INFECTION','active_infection','==',True,'withhold','Withhold during active infection.',10)]
setrules(d,rules);support(d,'high','nccp-parenteral-high');write(p,d)

# 00228 eribulin (shared)
p,d=load('00228');counts(d);standard_toxicity(d);defs=d['input_definitions'];defs['assessment_day']=select('Treatment day',[(1,'Day 1'),(8,'Day 8')],1);defs['eribulin_renal_band']=renal('Renal function for eribulin',[('ge50','CrCl ≥50 mL/min'),('lt50','CrCl <50 mL/min'),('dialysis','Haemodialysis')],'ge50');defs['child_pugh']=select('Child-Pugh class',[('normal','No hepatic impairment'),('A','Child-Pugh A'),('B','Child-Pugh B'),('C','Child-Pugh C')],'normal');defs['prolonged_anc_below_0_5_over_7d']=boolean('ANC <0.5 ×10⁹/L for >7 days in the previous cycle');defs['platelets_below_25_previous_cycle']=boolean('Platelets <25 ×10⁹/L in the previous cycle');defs['platelets_below_50_with_bleeding_or_transfusion']=boolean('Platelets <50 ×10⁹/L with haemorrhage or transfusion');defs['previous_grade_3_4_nonhaem']=boolean('Grade 3–4 non-haematological toxicity in previous cycle')
rules=common(d)+[
 r('ERIB_ANC_LT1','anc_x10e9_l','<',1,'delay','Day 1 or Day 8: ANC <1.0 ×10⁹/L requires delay/omission until recovery.',10,['eribulin']),r('ERIB_PLT_LT75','platelets_x10e9_l','<',75,'delay','Day 1 or Day 8: platelets <75 ×10⁹/L require delay/omission until recovery.',10,['eribulin']),r('ERIB_NONHAEM_G3','other_nonhaem_toxicity_grade','>=',3,'delay','Day 1 or Day 8: Grade 3–4 non-haematological toxicity requires delay until recovery.',10,['eribulin']),r('ERIB_PROLONGED_NEUT','prolonged_anc_below_0_5_over_7d','==',True,'dose_reduce_one_level','ANC <0.5 ×10⁹/L for >7 days: reduce eribulin by one dose level.',9,['eribulin']),r('ERIB_FN','febrile_neutropenia','==',True,'dose_reduce_one_level','ANC <1.0 ×10⁹/L with fever/infection: reduce eribulin by one dose level.',9,['eribulin']),r('ERIB_PLT25','platelets_below_25_previous_cycle','==',True,'dose_reduce_one_level','Platelets <25 ×10⁹/L: reduce eribulin by one dose level.',9,['eribulin']),r('ERIB_PLT50_BLEED','platelets_below_50_with_bleeding_or_transfusion','==',True,'dose_reduce_one_level','Platelets <50 ×10⁹/L with bleeding/transfusion: reduce eribulin by one dose level.',9,['eribulin']),r('ERIB_RENAL_LT50','eribulin_renal_band','==','lt50','dose_reduce','CrCl <50 mL/min: administer 80% eribulin.',8,['eribulin']),r('ERIB_HD','eribulin_renal_band','==','dialysis','dose_reduce','Haemodialysis: consider 80% eribulin with specialist review.',9,['eribulin']),r('ERIB_CP_A','child_pugh','==','A','dose_reduce','Child-Pugh A: administer 80% eribulin.',8,['eribulin']),r('ERIB_CP_B','child_pugh','==','B','dose_reduce','Child-Pugh B: administer 50% eribulin.',9,['eribulin']),r('ERIB_CP_C','child_pugh','==','C','contraindicated','Child-Pugh C: eribulin is not recommended.',10,['eribulin']),r('ERIB_PREV_G34','previous_grade_3_4_nonhaem','==',True,'dose_reduce_one_level','Previous Grade 3–4 non-haematological toxicity: reduce by one dose level.',9,['eribulin'])]
setrules(d,rules);write(p,d)

# 00501 gemcitabine/docetaxel
p,d=load('00501');counts(d);standard_toxicity(d);defs=d['input_definitions'];defs['assessment_day']=select('Treatment day',[(1,'Day 1'),(8,'Day 8'),(15,'Deferred Day 15')],1);defs['bilirubin_actual_umol_l']=number('Bilirubin',20,'µmol/L',1);defs['alt_ast_uln_multiple']=number('ALT/AST result (actual result; ×ULN calculated automatically)',1,'×ULN',.01);defs['alp_uln_multiple']=number('ALP multiple of ULN',1,'×ULN',.01);defs['neuropathy_grade']=grade('Peripheral neuropathy grade','neuropathy','Assess symptoms, dexterity, gait and effect on instrumental or self-care activities.');defs['second_febrile_neutropenia_occurrence']=boolean('Second febrile-neutropenia occurrence')
rules=common(d)+[
 r('DAY1_ANC','anc_x10e9_l','<',1,'delay','Day 1: ANC <1.0 ×10⁹/L requires delay until recovery.',10),r('DAY1_PLT','platelets_x10e9_l','<',100,'delay','Day 1: platelets <100 ×10⁹/L require delay until recovery.',10),r('DAY8_ANC','anc_x10e9_l','<',1,'delay','Day 8: ANC <1.0 ×10⁹/L requires deferral to Day 15; subsequent doses follow the source reduction pathway.',10),r('DAY8_PLT','platelets_x10e9_l','<',75,'delay','Day 8: platelets <75 ×10⁹/L require deferral to Day 15; subsequent doses follow the source reduction pathway.',10),r('FN_FIRST','febrile_neutropenia','==',True,'withhold','Febrile neutropenia: withhold the remainder of the cycle and consider G-CSF.',10),r('FN_SECOND','second_febrile_neutropenia_occurrence','==',True,'dose_reduce_one_level','Second febrile-neutropenia occurrence: reduce regimen by one dose level.',9),r('DOC_HEPATIC_NOT_REC','bilirubin_actual_umol_l','>',30,'contraindicated','Bilirubin >1.5 ×ULN: docetaxel is not recommended in the routine pathway.',10,['docetaxel']),r('DOC_HEPATIC_50','alt_ast_uln_multiple','>',5,'dose_reduce','Marked transaminase elevation: consider 50% docetaxel only within the source hepatic table and consultant review.',9,['docetaxel']),r('GEM_BILI_27','bilirubin_actual_umol_l','>=',27,'dose_reduce','Bilirubin ≥27 µmol/L: consider starting gemcitabine at 80% with close monitoring.',8,['gemcitabine']),r('NEURO_G2','neuropathy_grade','>=',2,'consultant_review','Grade ≥2 neuropathy requires docetaxel dose modification/omission review.',9,['docetaxel']),r('NONHAEM_G3','other_nonhaem_toxicity_grade','>=',3,'withhold_then_reduce','Grade ≥3 non-haematological toxicity: withhold until recovery and apply the source dose-reduction pathway.',9)]
setrules(d,rules);support(d,'low','nccp-parenteral-low');write(p,d)

# IE-VAC and IE common helper
for code in ['00675','00747','00596']:
 p,d=load(code);counts(d);standard_toxicity(d);ifos(d);defs=d['input_definitions'];defs['etoposide_renal_band']=renal('Renal function for etoposide',[('gt50','CrCl >50 mL/min'),('10_50','CrCl 10–50 mL/min'),('dialysis','Haemodialysis')],'gt50');defs['etoposide_hepatic_band']=select('Etoposide hepatic function',[('normal','Bilirubin ≤25 µmol/L and AST <60 U/L'),('moderate','Bilirubin 26–51 µmol/L or AST 60–180 U/L'),('severe','Bilirubin >51 µmol/L or AST >180 U/L')],'normal');defs['recovery_delay_beyond_protocol_day']=boolean('Counts not recovered by the protocol-defined latest treatment day')
 rules=common(d)+[
  r('ANC_LT075','anc_x10e9_l','<',.75,'delay','ANC <0.75 ×10⁹/L: delay one week.',10),r('PLT_LT100','platelets_x10e9_l','<',100,'delay','Platelets <100 ×10⁹/L: delay one week.',10),r('LATE_RECOVERY','recovery_delay_beyond_protocol_day','==',True,'dose_reduce','If counts have not recovered by the protocol-defined latest day, reduce subsequent doses by 20%.',9),r('ETO_CRCL_10_50','etoposide_renal_band','==','10_50','dose_reduce','CrCl 10–50 mL/min: administer 75% etoposide.',8,['etoposide']),r('ETO_HD','etoposide_renal_band','==','dialysis','dose_reduce','Haemodialysis: consider 75% etoposide with specialist timing review.',9,['etoposide']),r('ETO_HEP_MOD','etoposide_hepatic_band','==','moderate','dose_reduce','Bilirubin 26–51 µmol/L or AST 60–180 U/L: administer 50% etoposide.',8,['etoposide']),r('ETO_HEP_SEV','etoposide_hepatic_band','==','severe','consultant_review','Bilirubin >51 µmol/L or AST >180 U/L requires an individual clinical decision for etoposide.',10,['etoposide']),r('IFO_RENAL_LT50','ifosfamide_renal_band','==','lt50','consultant_review','CrCl <50 mL/min requires an individual decision for ifosfamide.',10,['ifosfamide']),r('IFO_DIALYSIS','ifosfamide_renal_band','==','dialysis','consultant_review','Dialysis requires an individual decision for ifosfamide.',10,['ifosfamide']),r('IFO_NEURO_G3','encephalopathy_grade','>=',3,'withhold','Grade 3–4 ifosfamide neurotoxicity requires immediate interruption and source-specific management.',10,['ifosfamide']),r('HAEMATURIA','haematuria','==',True,'withhold','Haematuria requires withholding ifosfamide and urothelial toxicity assessment.',10,['ifosfamide']),r('URINE','urine_output_below_target','==',True,'withhold','Inadequate urine output requires correction before continuing ifosfamide.',9,['ifosfamide'])]
 if code=='00596':
  rules += [r('MUCOSITIS_G3','mucositis_grade','>=',3,'dose_reduce','Grade 3–4 mucositis/stomatitis: reduce etoposide and ifosfamide by 25% after recovery.',9,['etoposide','ifosfamide'])]
 setrules(d,rules);support(d,'high','nccp-parenteral-high');write(p,d)

# 00680 high-dose ifosfamide
p,d=load('00680');counts(d);standard_toxicity(d);ifos(d);rules=common(d)+[
 r('ANC_LT1','anc_x10e9_l','<',1,'delay','ANC <1.0 ×10⁹/L: delay.',10),r('PLT_LT70','platelets_x10e9_l','<',70,'delay','Platelets <70 ×10⁹/L: delay.',10),r('ANC_1_1_5','anc_x10e9_l','<=',1.5,'dose_reduce','ANC 1.0–1.5 ×10⁹/L: administer 80% ifosfamide.',8,['ifosfamide']),r('PLT_70_100','platelets_x10e9_l','<=',100,'dose_reduce','Platelets 70–100 ×10⁹/L: administer 80% ifosfamide.',8,['ifosfamide']),r('FN_REDUCE','febrile_neutropenia','==',True,'dose_reduce','ANC nadir <0.5 ×10⁹/L with febrile neutropenia: administer 80% ifosfamide.',9,['ifosfamide']),r('IFO_RENAL_LT50','ifosfamide_renal_band','==','lt50','consultant_review','CrCl <50 mL/min: high-dose ifosfamide is not routinely recommended.',10,['ifosfamide']),r('IFO_DIALYSIS','ifosfamide_renal_band','==','dialysis','consultant_review','Dialysis: high-dose ifosfamide is not routinely recommended.',10,['ifosfamide']),r('MUCOSITIS_G3','mucositis_grade','>=',3,'dose_reduce','Grade ≥3 mucositis: administer 80% ifosfamide after recovery.',9,['ifosfamide']),r('NEURO_G3','encephalopathy_grade','>=',3,'permanently_discontinue','Grade ≥3 neurotoxicity: discontinue ifosfamide.',10,['ifosfamide']),r('HAEMATURIA','haematuria','==',True,'withhold','Haematuria requires withholding and urothelial toxicity assessment.',10,['ifosfamide']),r('URINE','urine_output_below_target','==',True,'withhold','Inadequate urine output requires correction before continuing.',9,['ifosfamide'])]
setrules(d,rules);support(d,'high','nccp-parenteral-high');write(p,d)

# 00504 irinotecan-temozolomide
p,d=load('00504');counts(d);standard_toxicity(d);defs=d['input_definitions'];defs['irinotecan_renal_band']=renal('Renal function for irinotecan',[('ge10','CrCl ≥10 mL/min'),('lt10','CrCl <10 mL/min'),('dialysis','Haemodialysis')],'ge10');defs['temozolomide_renal_band']=renal('Renal function for temozolomide',[('ge36','CrCl ≥36 mL/min'),('lt36','CrCl <36 mL/min'),('dialysis','Haemodialysis')],'ge36');defs['bilirubin_uln_multiple']=number('Bilirubin result (enter actual result; ×ULN calculated automatically)',1,'×ULN',.01);defs['delayed_count_recovery_14_days_or_more']=boolean('Count recovery delayed by ≥14 days');defs['recurrent_grade3_febrile_neutropenia']=boolean('Repeated Grade ≥3 febrile neutropenia after at least two cycles');defs['diarrhoea_grade']=grade('Diarrhoea grade','diarrhoea','Assess increase in stools over baseline, incontinence, need for IV fluids/admission and impact on self-care.');defs['acute_cholinergic_syndrome']=boolean('Acute irinotecan cholinergic syndrome')
rules=common(d)+[
 r('ANC_LT1','anc_x10e9_l','<',1,'delay','ANC <1.0 ×10⁹/L: delay treatment.',10),r('PLT_LT75','platelets_x10e9_l','<',75,'delay','Platelets <75 ×10⁹/L: delay treatment.',10),r('DELAYED_RECOVERY','delayed_count_recovery_14_days_or_more','==',True,'dose_reduce_one_level','Count recovery delayed by ≥14 days: reduce temozolomide by one dose level.',9,['temozolomide']),r('RECURRENT_FN','recurrent_grade3_febrile_neutropenia','==',True,'dose_reduce_one_level','Repeated Grade ≥3 febrile neutropenia: reduce temozolomide; prefer G-CSF where appropriate.',9,['temozolomide']),r('IRI_CRCL_LT10','irinotecan_renal_band','==','lt10','dose_reduce','CrCl <10 mL/min: use 50–66% irinotecan with specialist review.',9,['irinotecan']),r('IRI_DIALYSIS','irinotecan_renal_band','==','dialysis','dose_reduce','Haemodialysis: use 50–66% irinotecan with specialist timing review.',10,['irinotecan']),r('IRI_BILI_GT3','bilirubin_uln_multiple','>',3,'contraindicated','Bilirubin >3 ×ULN: irinotecan is contraindicated.',10,['irinotecan']),r('DIARRHOEA_G3','diarrhoea_grade','>=',3,'withhold_then_reduce','Grade ≥3 diarrhoea: withhold, actively treat and apply the source dose-reduction pathway after recovery.',10,['irinotecan']),r('CHOLINERGIC','acute_cholinergic_syndrome','==',True,'proceed_with_caution','Treat acute cholinergic syndrome with the protocol atropine pathway and reassess.',7,['irinotecan'])]
setrules(d,rules);support(d,'phase_dependent','nccp-parenteral-high');write(p,d)

# 00754 IVADo
p,d=load('00754');counts(d);standard_toxicity(d);anthracycline(d);ifos(d);defs=d['input_definitions'];defs['vincristine_bilirubin_band']=select('Bilirubin for vincristine',[('le51','Bilirubin ≤51 µmol/L'),('gt51','Bilirubin >51 µmol/L')],'le51');defs['age_years']=number('Age',18,'years',1)
rules=common(d)+[
 r('AGE_40','age_years','>=',40,'consultant_review','The routine IVADo source pathway is for patients under 40 years; verify specialist eligibility.',9),r('ANC_LT1','anc_x10e9_l','<',1,'delay','ANC <1.0 ×10⁹/L: delay one week.',10),r('PLT_LT80','platelets_x10e9_l','<',80,'delay','Platelets <80 ×10⁹/L: delay one week.',10),r('DOX_BILI_GT4_3','bilirubin_uln_multiple','>',4.3,'contraindicated','Bilirubin >86 µmol/L: doxorubicin not recommended.',10,['doxorubicin']),r('DOX_BILI_GT2_5','bilirubin_uln_multiple','>',2.5,'dose_reduce','Bilirubin 51–86 µmol/L: administer 25% doxorubicin.',9,['doxorubicin']),r('DOX_BILI_GT1','bilirubin_uln_multiple','>',1,'dose_reduce','Bilirubin 20–50 µmol/L: administer 50% doxorubicin.',8,['doxorubicin']),r('IFO_RENAL_LT50','ifosfamide_renal_band','==','lt50','consultant_review','CrCl <50 mL/min requires an individual decision for ifosfamide.',10,['ifosfamide']),r('IFO_DIALYSIS','ifosfamide_renal_band','==','dialysis','consultant_review','Dialysis requires an individual decision for ifosfamide.',10,['ifosfamide']),r('VIN_BILI','vincristine_bilirubin_band','==','gt51','dose_reduce','Bilirubin >51 µmol/L: administer 50% vincristine.',9,['vincristine']),r('MUCOSITIS_G3','mucositis_grade','>=',3,'dose_reduce','Grade ≥3 mucositis: reduce doxorubicin and ifosfamide to 80% after recovery.',9,['doxorubicin','ifosfamide']),r('IFO_NEURO_G3','encephalopathy_grade','>=',3,'permanently_discontinue','Grade ≥3 ifosfamide neurotoxicity: discontinue ifosfamide.',10,['ifosfamide'])]
setrules(d,rules);support(d,'phase_dependent','nccp-parenteral-high');write(p,d)

# 00335 imatinib GIST
p,d=load('00335');defs=d['input_definitions'];counts(d);standard_toxicity(d);defs['current_imatinib_dose_mg']=select('Current daily imatinib dose',[(400,'400 mg'),(300,'300 mg'),(200,'200 mg')],400);defs['alt_ast_uln_multiple']=number('ALT/AST result (enter actual result; ×ULN calculated automatically)',1,'×ULN',.01);defs['bilirubin_uln_multiple']=number('Bilirubin result (enter actual result; ×ULN calculated automatically)',1,'×ULN',.01);defs['other_nonhaem_toxicity_occurrence']=select('Occurrence of Grade 2–4 non-haematological toxicity',[(0,'None'),(1,'First occurrence'),(2,'Second occurrence'),(3,'Third or later occurrence')],0)
rules=common(d)+[
 r('IMAT_ANC_LT05','anc_x10e9_l','<',.5,'withhold_then_reduce','ANC <0.5 ×10⁹/L: hold until ≤Grade 1, then resume at the next lower dose level.',10,['imatinib']),r('IMAT_PLT_LT10','platelets_x10e9_l','<',10,'withhold_then_reduce','Platelets <10 ×10⁹/L: hold until ≤Grade 1, then resume at the next lower dose level.',10,['imatinib']),r('IMAT_ANC_LT1','anc_x10e9_l','<',1,'withhold_then_reduce','ANC 0.5–0.99 ×10⁹/L: hold until recovery and resume at a lower dose according to occurrence.',9,['imatinib']),r('IMAT_PLT_LT50','platelets_x10e9_l','<',50,'withhold_then_reduce','Platelets 10–49 ×10⁹/L: hold until recovery and resume at a lower dose according to occurrence.',9,['imatinib']),r('IMAT_BILI_GT3','bilirubin_uln_multiple','>',3,'withhold_then_reduce','Bilirubin >3 ×ULN: hold until <1.5 ×ULN, then resume at 300 mg.',10,['imatinib']),r('IMAT_TRANS_GT5','alt_ast_uln_multiple','>',5,'withhold_then_reduce','Transaminases >5 ×ULN: hold until <2.5 ×ULN, then resume at 300 mg.',10,['imatinib']),r('IMAT_OTHER_FIRST','other_nonhaem_toxicity_occurrence','==',1,'withhold','Clinically significant non-haematological toxicity: hold until recovery and follow the occurrence-based source pathway.',8,['imatinib']),r('IMAT_OTHER_REPEAT','other_nonhaem_toxicity_occurrence','>=',2,'dose_reduce_one_level','Recurrent non-haematological toxicity: resume at a lower imatinib dose after recovery.',9,['imatinib'])]
setrules(d,rules);write(p,d)

# 00463 MAP
p,d=load('00463');counts(d);standard_toxicity(d);anthracycline(d);defs=d['input_definitions'];defs['phase']=select('Current MAP phase',[('dox_cis','Doxorubicin/cisplatin phase'),('hdmtx','High-dose methotrexate phase')],'dox_cis');defs['methotrexate_renal_band']=renal('Renal function for high-dose methotrexate',[('adequate','Meets protocol renal criteria'),('impaired','Does not meet protocol renal criteria / significant decline')],'adequate');defs['urine_ph']=number('Urine pH before/during methotrexate',7.5,'',.1);defs['methotrexate_clearance_delayed']=boolean('Methotrexate clearance delayed');defs['folinic_acid_rescue_started_on_time']=boolean('Folinic acid rescue not started on time');defs['interacting_medicines_present']=boolean('Interacting medicines present around high-dose methotrexate');defs['cisplatin_renal_band']=renal('Renal function for cisplatin',[('adequate','Meets protocol cisplatin renal criteria'),('impaired','Does not meet protocol criteria / clinically significant decline')],'adequate')
rules=common(d)+[
 r('MAP_ANC_DOXCIS','anc_x10e9_l','<',.75,'delay','Doxorubicin/cisplatin phase: ANC <0.75 ×10⁹/L requires delay.',10),r('MAP_PLT_DOXCIS','platelets_x10e9_l','<',75,'delay','Doxorubicin/cisplatin phase: platelets <75 ×10⁹/L require delay.',10),r('MAP_ANC_MTX','anc_x10e9_l','<',.25,'delay','High-dose methotrexate phase: ANC <0.25 ×10⁹/L requires delay.',10),r('MAP_PLT_MTX','platelets_x10e9_l','<',50,'delay','High-dose methotrexate phase: platelets <50 ×10⁹/L require delay.',10),r('MAP_FN','febrile_neutropenia','==',True,'consultant_review','Febrile neutropenia: add G-CSF; further episodes trigger cisplatin reduction according to source.',9),r('MAP_DOX_BILI_GT4_35','bilirubin_uln_multiple','>',4.35,'omit','Bilirubin >87 µmol/L: omit doxorubicin.',10,['doxorubicin']),r('MAP_DOX_BILI_GT2_6','bilirubin_uln_multiple','>',2.6,'dose_reduce','Bilirubin 53–86 µmol/L: administer 25% doxorubicin.',9,['doxorubicin']),r('MAP_DOX_BILI_GT1_75','bilirubin_uln_multiple','>',1.75,'dose_reduce','Bilirubin 36–52 µmol/L: administer 50% doxorubicin.',9,['doxorubicin']),r('MAP_DOX_BILI_GT1_05','bilirubin_uln_multiple','>',1.05,'dose_reduce','Bilirubin 22–35 µmol/L: administer 75% doxorubicin.',8,['doxorubicin']),r('MAP_LVEF','lvef_percent','<',50,'omit','Persistently abnormal LVEF (<50%) after repeat assessment: omit further doxorubicin.',10,['doxorubicin']),r('MAP_MUCOSITIS_G4','mucositis_grade','>=',4,'dose_reduce','Grade 4 or repeated Grade 3 mucositis: reduce doxorubicin to 60 mg/m² per course.',9,['doxorubicin']),r('MAP_MTX_RENAL','methotrexate_renal_band','==','impaired','withhold','Do not commence high-dose methotrexate until protocol renal criteria are met.',10,['methotrexate']),r('MAP_URINE_PH','urine_ph','<',7,'withhold','Urine pH below 7: continue alkalinisation; do not commence/continue methotrexate until target is achieved.',10,['methotrexate']),r('MAP_DELAYED_CLEARANCE','methotrexate_clearance_delayed','==',True,'withhold','Delayed methotrexate clearance: intensify hydration/alkalinisation and folinic-acid rescue per level-based pathway.',10,['methotrexate']),r('MAP_RESCUE_LATE','folinic_acid_rescue_started_on_time','==',True,'withhold','Folinic-acid rescue not started on time: urgent senior/pharmacy review.',10,['methotrexate']),r('MAP_INTERACTIONS','interacting_medicines_present','==',True,'withhold','Potential high-dose methotrexate interaction: withhold interacting medicine and obtain pharmacy review.',10,['methotrexate']),r('MAP_CIS_RENAL','cisplatin_renal_band','==','impaired','consultant_review','Renal function does not meet the cisplatin pathway: specialist dose/substitution review required.',10,['cisplatin'])]
setrules(d,rules);support(d,'phase_dependent','nccp-parenteral-high');write(p,d)

# 00100 mifamurtide
p,d=load('00100');defs=d['input_definitions'];defs['age_years']=number('Age',18,'years',1);defs['metastatic_at_presentation']=boolean('Metastatic disease at presentation');defs['macroscopically_complete_resection']=boolean('Macroscopically complete resection not achieved');defs['prior_non_preoperative_treatment']=boolean('Prior treatment outside the protocol preoperative pathway');defs['mifamurtide_renal_band']=renal('Renal function for mifamurtide',[('ge30','CrCl ≥30 mL/min'),('lt30','CrCl <30 mL/min'),('dialysis','Dialysis')],'ge30');defs['child_pugh']=select('Hepatic function',[('normal','Normal'),('A','Child-Pugh A'),('B','Child-Pugh B'),('C','Severe hepatic impairment')],'normal');defs['infusion_reaction_grade']=grade('Infusion-related reaction grade','infusion','Assess fever/chills, rash, dyspnoea, hypotension, intervention required and recovery.');defs['unstable_cardiovascular_or_thrombotic_disorder']=boolean('Unstable cardiovascular disorder, vasculitis or active significant thrombosis');defs['high_dose_nsaid_use']=boolean('High-dose NSAID use');defs['chronic_systemic_corticosteroids']=boolean('Chronic systemic corticosteroids or immunosuppression')
rules=common(d)+[
 r('AGE_LT2','age_years','<',2,'contraindicated','Age <2 years is outside the source indication.',10),r('AGE_GT30','age_years','>',30,'consultant_review','Age >30 years is outside the routine source indication.',9),r('METASTATIC_PRESENTATION','metastatic_at_presentation','==',True,'contraindicated','Metastatic disease at presentation is outside the source indication.',10),r('INCOMPLETE_RESECTION','macroscopically_complete_resection','==',True,'contraindicated','Macroscopically complete resection is required for the source indication.',10),r('PRIOR_TREATMENT','prior_non_preoperative_treatment','==',True,'consultant_review','Prior treatment outside the source preoperative pathway requires specialist eligibility review.',9),r('RENAL_LT30','mifamurtide_renal_band','==','lt30','consultant_review','CrCl <30 mL/min: limited data; use only after careful specialist review.',9),r('RENAL_HD','mifamurtide_renal_band','==','dialysis','consultant_review','Dialysis: no routine dosing data; specialist review required.',10),r('HEP_B','child_pugh','==','B','proceed_with_caution','Child-Pugh B: use with caution and close monitoring.',7),r('HEP_C','child_pugh','==','C','consultant_review','Severe hepatic impairment: no routine dosing data.',9),r('INFUSION_G3','infusion_reaction_grade','>=',3,'withhold','Grade ≥3 infusion reaction: interrupt and obtain specialist review.',10),r('CV','unstable_cardiovascular_or_thrombotic_disorder','==',True,'consultant_review','Unstable cardiovascular/thrombotic disease requires benefit-risk review.',9),r('NSAID','high_dose_nsaid_use','==',True,'contraindicated','High-dose NSAID use is incompatible with the routine mifamurtide pathway.',10),r('STEROID','chronic_systemic_corticosteroids','==',True,'consultant_review','Chronic systemic corticosteroid/immunosuppressive therapy may reduce effect and requires review.',8)]
setrules(d,rules);support(d,'moderate','nccp-parenteral-moderate');write(p,d)

# 00445 pazopanib
p,d=load('00445');counts(d);standard_toxicity(d);defs=d['input_definitions'];defs['pazopanib_renal_band']=renal('Renal function for pazopanib',[('ge30','CrCl ≥30 mL/min'),('lt30','CrCl <30 mL/min'),('dialysis','Dialysis')],'ge30');defs['alt_ast_uln_multiple']=number('ALT/AST result (enter actual result; ×ULN calculated automatically)',1,'×ULN',.01);defs['bilirubin_uln_multiple']=number('Bilirubin result (enter actual result; ×ULN calculated automatically)',1,'×ULN',.01);defs['recurrent_alt_after_restart']=boolean('ALT recurred >3 ×ULN after reduced-dose restart');defs['uncontrolled_hypertension']=boolean('Uncontrolled hypertension');defs['qtcf_ms']=number('QTcF',430,'ms',1);defs['symptomatic_cardiac_dysfunction']=boolean('Symptomatic cardiac dysfunction');defs['clinically_significant_bleeding']=boolean('Clinically significant bleeding');defs['rash_or_hfsr_grade']=grade('Hand-foot skin reaction / rash grade','rash','Assess painful erythema, swelling, blistering, body-surface area and impact on instrumental or self-care activities.')
rules=common(d)+[
 r('ANC_LT1','anc_x10e9_l','<',1,'delay','ANC <1.0 ×10⁹/L: delay pazopanib.',10),r('PLT_LT75','platelets_x10e9_l','<',75,'delay','Platelets <75 ×10⁹/L: delay pazopanib.',10),r('RENAL_LT30','pazopanib_renal_band','==','lt30','proceed_with_caution','CrCl <30 mL/min: use with caution; limited data.',7),r('RENAL_HD','pazopanib_renal_band','==','dialysis','consultant_review','Dialysis: specialist dosing review required.',9),r('BILI_GT3','bilirubin_uln_multiple','>',3,'contraindicated','Bilirubin >3 ×ULN: pazopanib is contraindicated.',10,['pazopanib']),r('BILI_1_5_3','bilirubin_uln_multiple','>',1.5,'dose_reduce','Bilirubin 1.5–3 ×ULN: use 200 mg daily.',9,['pazopanib']),r('ALT_GT8','alt_ast_uln_multiple','>',8,'withhold','ALT >8 ×ULN: interrupt pazopanib and monitor.',10,['pazopanib']),r('ALT_3_8','alt_ast_uln_multiple','>',3,'proceed_with_caution','ALT 3–8 ×ULN: continue with weekly liver monitoring if otherwise appropriate.',7,['pazopanib']),r('RECURRENT_ALT','recurrent_alt_after_restart','==',True,'permanently_discontinue','Recurrent ALT >3 ×ULN after reduced-dose restart: permanently discontinue pazopanib.',10,['pazopanib']),r('ALT_BILI_COMBO','bilirubin_uln_multiple','>',2,'permanently_discontinue','ALT >3 ×ULN with bilirubin >2 ×ULN requires permanent discontinuation; confirm both values.',10,['pazopanib']),r('HFSR_G3','rash_or_hfsr_grade','>=',3,'withhold_then_reduce','Grade 3 HFSR/rash: interrupt until recovery and resume at a lower dose.',9,['pazopanib']),r('BP','uncontrolled_hypertension','==',True,'withhold','Withhold until blood pressure is controlled.',10,['pazopanib']),r('QTC','qtcf_ms','>=',500,'withhold','QTcF ≥500 ms: interrupt and correct reversible causes.',10,['pazopanib']),r('CARDIAC','symptomatic_cardiac_dysfunction','==',True,'withhold','Symptomatic cardiac dysfunction requires interruption and cardiac assessment.',10,['pazopanib']),r('BLEED','clinically_significant_bleeding','==',True,'withhold','Clinically significant bleeding requires interruption and specialist review.',10,['pazopanib']),r('OTHER_G3','other_nonhaem_toxicity_grade','>=',3,'withhold_then_reduce','Grade 3–4 toxicity: delay until Grade ≤1 and reduce one dose level.',9,['pazopanib'])]
setrules(d,rules);write(p,d)

# PLD protocols 00205 and 00462
for code in ['00205','00462']:
 p,d=load(code);counts(d);standard_toxicity(d);anthracycline(d);defs=d['input_definitions'];defs['ppe_grade']=grade('Palmar-plantar erythrodysesthesia grade','ppe','Assess painful erythema, swelling, blistering, functional limitation and impact on instrumental or self-care activities.');defs['stomatitis_grade']=grade('Stomatitis grade','mucositis','Assess pain, ulceration, oral intake and nutritional consequences.')
 if code=='00205':
  rules=common(d)+[r('ANC_LT05','anc_x10e9_l','<',.5,'withhold_then_reduce','ANC <0.5 ×10⁹/L: hold until recovery, then reduce PLD by 25% or use G-CSF.',10,['pegylated liposomal doxorubicin']),r('PLT_LT25','platelets_x10e9_l','<',25,'withhold_then_reduce','Platelets <25 ×10⁹/L: hold until recovery, then reduce PLD by 25% or use G-CSF.',10,['pegylated liposomal doxorubicin']),r('ANC_LT15','anc_x10e9_l','<',1.5,'withhold','ANC <1.5 ×10⁹/L: hold until recovery; no routine dose reduction for this band.',9,['pegylated liposomal doxorubicin']),r('PLT_LT75','platelets_x10e9_l','<',75,'withhold','Platelets <75 ×10⁹/L: hold until recovery; no routine dose reduction for this band.',9,['pegylated liposomal doxorubicin'])]
 else:
  rules=common(d)+[r('ANC_LT05','anc_x10e9_l','<',.5,'delay','ANC <0.5 ×10⁹/L: delay treatment.',10,['pegylated liposomal doxorubicin']),r('PLT_LT50','platelets_x10e9_l','<',50,'delay','Platelets <50 ×10⁹/L: delay treatment.',10,['pegylated liposomal doxorubicin']),r('ANC_05_099','anc_x10e9_l','<',1,'dose_reduce','ANC 0.5–0.99 ×10⁹/L: administer 50% PLD.',8,['pegylated liposomal doxorubicin']),r('PLT_50_74','platelets_x10e9_l','<',75,'dose_reduce','Platelets 50–74 ×10⁹/L: administer 50% PLD.',8,['pegylated liposomal doxorubicin'])]
 rules += [r('PLD_BILI_GT4_3','bilirubin_uln_multiple','>',4.3,'contraindicated','Bilirubin >86 µmol/L: PLD is not recommended.',10,['pegylated liposomal doxorubicin']),r('PLD_BILI_GT2_5','bilirubin_uln_multiple','>',2.5,'dose_reduce','Bilirubin 51–86 µmol/L: administer 50% PLD.',9,['pegylated liposomal doxorubicin']),r('PLD_BILI_GT1','bilirubin_uln_multiple','>',1,'dose_reduce','Bilirubin 20–50 µmol/L: administer 75% PLD.',8,['pegylated liposomal doxorubicin']),r('PPE_G2','ppe_grade','>=',2,'withhold_then_reduce','Grade ≥2 PPE: delay until recovery and apply the grade/duration-specific PLD reduction pathway.',9,['pegylated liposomal doxorubicin']),r('STOMATITIS_G2','stomatitis_grade','>=',2,'withhold_then_reduce','Grade ≥2 stomatitis: delay until recovery and apply the grade/duration-specific PLD reduction pathway.',9,['pegylated liposomal doxorubicin']),r('CARDIAC','symptomatic_cardiac_dysfunction','==',True,'withhold','Cardiac symptoms require withholding and cardiac assessment.',10,['pegylated liposomal doxorubicin'])]
 setrules(d,rules);support(d,'low','nccp-parenteral-low');write(p,d)

# 00374 trabectedin
p,d=load('00374');counts(d);standard_toxicity(d);defs=d['input_definitions'];defs['alt_ast_uln_multiple']=number('ALT/AST result (enter actual result; ×ULN calculated automatically)',1,'×ULN',.01);defs['bilirubin_uln_multiple']=number('Bilirubin result (enter actual result; ×ULN calculated automatically)',1,'×ULN',.01);defs['alp_uln_multiple']=number('ALP multiple of ULN',1,'×ULN',.01);defs['ck_uln_multiple']=number('CK multiple of ULN',1,'×ULN',.01);defs['symptomatic_muscle_toxicity']=boolean('Muscle pain/weakness or suspected rhabdomyolysis');defs['trabectedin_renal_band']=renal('Renal function for trabectedin',[('any_non_dialysis','Any non-dialysis renal function'),('dialysis','Haemodialysis')],'any_non_dialysis');defs['hepatic_impairment_band']=select('Hepatic impairment',[('none','None'),('moderate','Moderate'),('severe','Severe')],'none');defs['lvef_below_lln_or_cardiomyopathy']=boolean('LVEF below LLN or cardiomyopathy');defs['persistent_or_symptomatic_cardiac_dysfunction']=boolean('Persistent or symptomatic cardiac dysfunction')
rules=common(d)+[
 r('ANC_LT15','anc_x10e9_l','<',1.5,'delay','ANC <1.5 ×10⁹/L: delay trabectedin until recovery.',10),r('PLT_LT100','platelets_x10e9_l','<',100,'delay','Platelets <100 ×10⁹/L: delay trabectedin until recovery.',10),r('BILI','bilirubin_uln_multiple','>',1,'dose_reduce_one_level','Bilirubin above ULN during the previous cycle: reduce trabectedin by one dose level after recovery.',10,['trabectedin']),r('ASTALT','alt_ast_uln_multiple','>',2.5,'dose_reduce_one_level','AST/ALT >2.5 ×ULN during the previous cycle: reduce trabectedin by one dose level after recovery.',9,['trabectedin']),r('ALP','alp_uln_multiple','>',2.5,'dose_reduce_one_level','ALP >2.5 ×ULN: reduce trabectedin by one dose level after recovery.',9,['trabectedin']),r('CK','ck_uln_multiple','>',2.5,'withhold','CK >2.5 ×ULN: withhold and assess for myotoxicity/rhabdomyolysis.',10,['trabectedin']),r('RHABDO','symptomatic_muscle_toxicity','==',True,'permanently_discontinue','Suspected rhabdomyolysis: permanently discontinue trabectedin and urgently assess.',10,['trabectedin']),r('HD','trabectedin_renal_band','==','dialysis','consultant_review','Haemodialysis: specialist review; routine data are limited.',9,['trabectedin']),r('HEP_MOD','hepatic_impairment_band','==','moderate','dose_reduce','Moderate hepatic impairment: use 60% trabectedin.',9,['trabectedin']),r('HEP_SEV','hepatic_impairment_band','==','severe','contraindicated','Severe hepatic impairment: trabectedin is not recommended.',10,['trabectedin']),r('CARDIAC_DELAY','lvef_below_lln_or_cardiomyopathy','==',True,'withhold_then_reduce','LVEF below LLN/cardiomyopathy: delay up to 3 weeks; reduce after a prior-cycle event.',9,['trabectedin']),r('CARDIAC_STOP','persistent_or_symptomatic_cardiac_dysfunction','==',True,'permanently_discontinue','Persistent or symptomatic cardiac dysfunction: discontinue trabectedin.',10,['trabectedin']),r('OTHER_G3','other_nonhaem_toxicity_grade','>=',3,'dose_reduce_one_level','Grade 3–4 adverse event: reduce trabectedin by one dose level after recovery.',9,['trabectedin'])]
setrules(d,rules);support(d,'low','nccp-parenteral-low');write(p,d)

# 00554 vinblastine/methotrexate
p,d=load('00554');counts(d);standard_toxicity(d);defs=d['input_definitions'];defs['methotrexate_renal_band']=renal('Renal function for methotrexate',[('gt80','CrCl >80 mL/min'),('60_80','CrCl 60–80 mL/min'),('45_59','CrCl 45–59 mL/min'),('30_44','CrCl 30–44 mL/min'),('lt30','CrCl <30 mL/min'),('dialysis','Dialysis')],'gt80');defs['methotrexate_hepatic_band']=select('Methotrexate hepatic function',[('normal','Bilirubin <50 µmol/L and AST <180 U/L'),('moderate','Bilirubin 51–85 µmol/L or AST >180 U/L'),('severe','Bilirubin >85 µmol/L')],'normal');defs['vinblastine_hepatic_band']=select('Vinblastine hepatic function',[('normal','Bilirubin ≤25 µmol/L and AST <60 U/L'),('half','Bilirubin 26–51 µmol/L or AST 60–180 U/L'),('omit','Bilirubin >51 µmol/L with AST >180 U/L')],'normal');defs['vinca_neuropathy_grade']=grade('Vinca-associated neuropathy grade','neuropathy','Assess sensory/motor symptoms, ileus/constipation, gait, dexterity and effect on activities.');defs['third_space_fluid_significant']=boolean('Significant pleural effusion, ascites or other third-space fluid')
rules=common(d)+[
 r('ANC_LT05','anc_x10e9_l','<',.5,'delay','ANC <0.5 ×10⁹/L: delay treatment.',10),r('PLT_LT50','platelets_x10e9_l','<',50,'delay','Platelets <50 ×10⁹/L: delay treatment.',10),r('ANC_05_09','anc_x10e9_l','<=',.9,'dose_reduce','ANC 0.5–0.9 ×10⁹/L: administer 50% vinblastine and methotrexate.',8,['vinblastine','methotrexate']),r('PLT_50_99','platelets_x10e9_l','<=',99,'dose_reduce','Platelets 50–99 ×10⁹/L: administer 50% vinblastine and methotrexate.',8,['vinblastine','methotrexate']),r('MTX_CRCL_60_80','methotrexate_renal_band','==','60_80','dose_reduce','CrCl 60–80 mL/min: administer 65% methotrexate.',8,['methotrexate']),r('MTX_CRCL_45_59','methotrexate_renal_band','==','45_59','dose_reduce','CrCl 45–59 mL/min: administer 50% methotrexate.',9,['methotrexate']),r('MTX_CRCL_30_44','methotrexate_renal_band','==','30_44','consultant_review','CrCl 30–44 mL/min: individual clinical/pharmacy decision for methotrexate.',10,['methotrexate']),r('MTX_CRCL_LT30','methotrexate_renal_band','==','lt30','contraindicated','CrCl <30 mL/min: methotrexate is contraindicated.',10,['methotrexate']),r('MTX_HD','methotrexate_renal_band','==','dialysis','contraindicated','Dialysis: methotrexate is contraindicated in the routine pathway.',10,['methotrexate']),r('MTX_HEP_MOD','methotrexate_hepatic_band','==','moderate','dose_reduce','Bilirubin 51–85 µmol/L or AST >180 U/L: administer 75% methotrexate.',8,['methotrexate']),r('MTX_HEP_SEV','methotrexate_hepatic_band','==','severe','contraindicated','Bilirubin >85 µmol/L: methotrexate is contraindicated.',10,['methotrexate']),r('VBL_HEP_HALF','vinblastine_hepatic_band','==','half','dose_reduce','Moderate hepatic dysfunction: administer 50% vinblastine.',8,['vinblastine']),r('VBL_HEP_OMIT','vinblastine_hepatic_band','==','omit','omit','Severe combined bilirubin/AST elevation: omit vinblastine.',10,['vinblastine']),r('NEURO_G2','vinca_neuropathy_grade','>',2,'consultant_review','Neuropathy >Grade 2: consultant-led vinblastine reduction/omission review.',9,['vinblastine']),r('MUCOSITIS_G1','mucositis_grade','>=',1,'dose_reduce','Grade 1 mucositis: reduce methotrexate by 50%.',7,['methotrexate']),r('MUCOSITIS_G2','mucositis_grade','>=',2,'omit','Grade ≥2 mucositis: omit methotrexate until recovery and reassess.',10,['methotrexate']),r('THIRD_SPACE','third_space_fluid_significant','==',True,'consultant_review','Significant third-space fluid requires reconsideration because methotrexate elimination may be delayed.',9,['methotrexate'])]
setrules(d,rules);support(d,'low','nccp-parenteral-low');write(p,d)

# 00757 VIT
p,d=load('00757');counts(d);standard_toxicity(d);defs=d['input_definitions'];defs['age_years']=number('Age',18,'years',1);defs['irinotecan_renal_band']=renal('Renal function for irinotecan',[('ge10','CrCl ≥10 mL/min'),('lt10','CrCl <10 mL/min'),('dialysis','Haemodialysis')],'ge10');defs['temozolomide_renal_band']=renal('Renal function for temozolomide',[('ge36','CrCl ≥36 mL/min'),('lt36','CrCl <36 mL/min'),('dialysis','Haemodialysis')],'ge36');defs['bilirubin_uln_multiple']=number('Bilirubin result (enter actual result; ×ULN calculated automatically)',1,'×ULN',.01);defs['diarrhoea_grade']=grade('Diarrhoea grade','diarrhoea','Assess increase in stools over baseline, incontinence, need for IV fluids/admission and impact on self-care.');defs['diarrhoea_duration_days']=number('Duration of clinically significant diarrhoea',0,'days',1);defs['diarrhoea_recurrence']=boolean('Recurrent Grade ≥3 diarrhoea');defs['vinca_neuropathy_grade']=grade('Vincristine-associated neuropathy grade','neuropathy','Assess sensory/motor symptoms, gait, dexterity, ileus and impact on instrumental or self-care activities.');defs['acute_cholinergic_syndrome']=boolean('Acute irinotecan cholinergic syndrome')
rules=common(d)+[
 r('AGE_GT50','age_years','>',50,'consultant_review','Age >50 years is outside the routine source age range.',9),r('ANC_LT1','anc_x10e9_l','<',1,'delay','ANC <1.0 ×10⁹/L: delay according to the cycle/day source pathway.',10),r('PLT_LT75','platelets_x10e9_l','<',75,'delay','Platelets <75 ×10⁹/L: delay according to the cycle/day source pathway.',10),r('IRI_CRCL_LT10','irinotecan_renal_band','==','lt10','dose_reduce','CrCl <10 mL/min: use 50–66% irinotecan with specialist review.',9,['irinotecan']),r('IRI_HD','irinotecan_renal_band','==','dialysis','dose_reduce','Haemodialysis: use 50–66% irinotecan with specialist timing review.',10,['irinotecan']),r('IRI_BILI_GT3','bilirubin_uln_multiple','>',3,'contraindicated','Bilirubin >3 ×ULN: irinotecan is contraindicated.',10,['irinotecan']),r('DIARRHOEA_G3','diarrhoea_grade','>=',3,'dose_reduce','Grade ≥3 diarrhoea lasting ≥3 days: reduce irinotecan/temozolomide according to the source occurrence pathway.',9,['irinotecan','temozolomide']),r('DIARRHOEA_GT14','diarrhoea_duration_days','>',14,'permanently_discontinue','Clinically significant diarrhoea persisting >2 weeks: discontinue the affected treatment pathway.',10),r('DIARRHOEA_REC','diarrhoea_recurrence','==',True,'dose_reduce_one_level','Recurrent Grade ≥3 diarrhoea: apply a further dose reduction; repeated recurrence may require discontinuation.',9),r('NONHAEM_G3','other_nonhaem_toxicity_grade','>=',3,'dose_reduce','Grade 3 non-haematological toxicity: reduce irinotecan and temozolomide after recovery.',9,['irinotecan','temozolomide']),r('NONHAEM_G4','other_nonhaem_toxicity_grade','>=',4,'permanently_discontinue','Grade 4 non-haematological toxicity: discontinue the affected treatment pathway.',10),r('VIN_NEURO_G2','vinca_neuropathy_grade','>=',2,'withhold_then_reduce','Grade 2 vincristine neurotoxicity: hold until recovery, then resume at 50%.',9,['vincristine']),r('VIN_NEURO_G3','vinca_neuropathy_grade','>=',3,'omit','Grade 3–4 vincristine neurotoxicity: omit vincristine.',10,['vincristine']),r('CHOLINERGIC','acute_cholinergic_syndrome','==',True,'proceed_with_caution','Treat acute cholinergic syndrome with the atropine pathway.',7,['irinotecan'])]
setrules(d,rules);support(d,'phase_dependent','nccp-parenteral-high');write(p,d)

# Update remaining protocols' source validation markers and remove known overly prescriptive generic ifos neuro rule mismatch
for code in ['00244','00325','00719']:
 p,d=load(code);d['metadata']['sactcheck_encoding_version']='0.41.0';d['metadata']['partial_assessment_supported']=True;d['required_inputs']=[];write(p,d)

print('Reconciled Sarcoma source-specific rules for v0.41.0')
